
## Uses the OPENAI_BASE_URL environment variable by default. You can also uncomment bellow to set it.
AIBaseURL "http://localhost:8880/v1"

## Uses the OPENAI_API_KEY environment variable by default. You can also uncomment bellow to set it.
AIKey "not needed for local"

## If you use Kokoro FastAPI (https://github.com/remsky/Kokoro-FastAPI)
AIDefaultModel "kokoro"

## Kokoro voices:
##
AddVoice "en" "male1" "am_fenrir"
AddVoice "en" "male2" "am_michael"
AddVoice "en" "male2" "bm_george"
AddVoice "en" "female1" "af_heart"
AddVoice "en" "female2" "af_bella"
AddVoice "en" "female2" "bf_emma"
AddVoice "fr" "female1" "ff_siwis"

DefaultVoice "af_bella"