
## Uses the OPENAI_BASE_URL environment variable by default. You can also uncomment bellow to set it.
# AIBaseURL "http://localhost:8880/v1"
AIBaseURL "http://localhost:59113/v1"

## Uses the OPENAI_API_KEY environment variable by default. You can also uncomment bellow to set it.
AIKey "not needed for local"

#AIDefaultModel "tts-1"
AIDefaultModel "supertonic-3"
DefaultVoice F1
DefaultSpeed 1.2 

